export { TILE_SIZE, PLAYER_SPEED, PROXIMITY_RADIUS, MOVEMENT_EMIT_INTERVAL, MAP_DEFAULT_WIDTH, MAP_DEFAULT_HEIGHT, MAP_MAX_WIDTH, MAP_MAX_HEIGHT, SPRITE_WIDTH, SPRITE_HEIGHT, ANIMATION_FRAME_RATE, CHAT_MAX_LENGTH, DISPLAY_NAME_MAX_LENGTH, PROXIMITY_CHAT_FADE_MS, MAX_MEETING_MESH_PEERS, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, SPACE_MAX_MEMBERS_DEFAULT, SPACE_NAME_MAX_LENGTH, SPACE_SLUG_MAX_LENGTH, INVITATION_EXPIRY_DAYS } from './game';
export { SpaceRole, ROLE_HIERARCHY } from './roles';
export type { SpaceRoleType } from './roles';
export { Permission, DEFAULT_PERMISSIONS } from './permissions';
export type { PermissionType } from './permissions';
